import { Colors } from 'react-native/Libraries/NewAppScreen';
import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    scrollView: {
        backgroundColor: 'white',
    },
    loginForm: {
        borderColor: 'lightgray',
        // backgroundColor: 'white',
        // borderWidth: 1,
        padding: 20,
        marginHorizontal: 20,
        marginTop: -100,
        borderRadius: 5,
    },
    loginFormRegister: {
        // borderColor: 'lightgray',
        // backgroundColor: 'white',
        // borderWidth: 1,
        padding: 20,
        marginHorizontal: 20,
        marginTop: -100,
        borderRadius: 5,
    },
    homeContainer: {
        backgroundColor: '#FAFAFA',
        padding: 20,
        // flex: 1,
        // paddingBottom: 5,

        // shadowColor: "#454D65",
        // shadowOffset: { height: 5 },
        // shadowRadius: 7,
        // shadowOpacity: 0.1,
        borderBottomColor: '#E0E0E0',
        borderBottomWidth: StyleSheet.hairlineWidth,
        // justifyContent: 'center',
        // alignItems: 'center',
        // flexDirection: 'row',
        // borderColor: 'black',
        // borderWidth: 1,
    },
    avatar: {
        width: 100,
        height: 100,
        borderRadius: 50,
    },
    loginInputText: {
        borderColor: 'white',
        backgroundColor: 'white',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderWidth: 1,
        marginBottom: 20,
        borderRadius: 5,
        shadowColor: "#454D65",
        shadowOffset: { height: 7 },
        shadowRadius: 5,
        shadowOpacity: 0.25,
    },
    loginInputTextProfile: {
        borderColor: 'white',
        backgroundColor: 'white',
        marginTop: 25,
        paddingVertical: 12,
        paddingHorizontal: 100,
        borderWidth: 1,
        borderRadius: 5,
        shadowColor: "#454D65",
        shadowOffset: { height: 7, },
        shadowRadius: 5,
        shadowOpacity: 0.1,
    },
    engine: {
        position: 'absolute',
        right: 0,
    },
    body: {
        backgroundColor: 'black',
    },
    sectionContainer: {
        marginTop: 32,
        paddingHorizontal: 24,
    },
    sectionTitle: {
        fontSize: 24,
        fontWeight: '600',
        color: Colors.black,
    },
    sectionDescription: {
        marginTop: 8,
        fontSize: 18,
        fontWeight: '400',
        color: Colors.dark,
    },
    highlight: {
        fontWeight: '700',
    },
    footer: {
        color: Colors.dark,
        fontSize: 12,
        fontWeight: '600',
        padding: 4,
        paddingRight: 12,
        textAlign: 'right',
    },
    profileAvatar: {
        width: 70,
        height: 70,
        borderRadius: 50,
        left: 10,
    },
    avatarAdd: {
        position: 'absolute',
        top: 50,
        left: 60,
        // borderColor: 'white',
        // borderWidth: 20,
        // borderRadius: 50,
        // width: 70,
        // height: 70,
        // borderRadius: 50,
        // left: 10,
    },
    statsContainer: {
        position: 'absolute',
        flexDirection: 'row',
        paddingVertical: 10,
        right: 35,
        top: 30,
    },
    statsNumbers: {
        textAlign: 'center',
        fontWeight: '600',
        fontSize: 17,
    },
    statsTexts: {
        textAlign: 'center',
        fontSize: 15,
        fontWeight: '200',
    },
    statsMiddleBox: {
        borderLeftColor: 'lightgrey',
        borderLeftWidth: StyleSheet.hairlineWidth,
        borderRightColor: 'lightgrey',
        borderRightWidth: StyleSheet.hairlineWidth,
        paddingHorizontal: 20,
        marginHorizontal: 20,
        textAlign: 'center',
    },
});

export default styles;